### ISSUE TITLE
Any support for Angular 6

### ISSUE THREAD

**Issue by B-PRAVEEN** [cssninjaStudio/bulkit-public#17]
Can we separate HTML, SCSS AND JS code

**Comment by cssninjaStudio** [comment]
Yes you can separate SCSS and HTML to work with angular and create components. However, I strongly recommend that the styles are merged in a single stylesheet during the build process. Style variables should be available globally in the project for better performance. For JS, you sinply have to ditch it and rewrite your own since it's jQuery based.

**Comment by theo-stocchetti** [comment]
Closed following the answer provided, you can reopen this ticket if you have a similar topic to discuss.
